version: '3.8'

services:
  jenkins:
    build: .
    container_name: mlops_jenkins
    restart: unless-stopped
    privileged: true
    shm_size: '2gb'
    user: root 
    ports:
      - "8080:8080"   # The Jenkins Web UI
      - "50000:50000" # Attached Jenkins agents
      - "8000:8000"   # Exposes Ray Serve / FastAPI to your local browser
    volumes:
      - jenkins_home:/var/jenkins_home
      # Optional: Uncomment the line below if your Jenkins pipelines need to run Docker commands themselves (Docker-in-Docker)
      # - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  jenkins_home: